// Client for the MPLADS Oversight API. Hand-written — unlike js/pages, js/state
// and js/data, this file is not regenerated by tools/jsxify.mjs.

const BASE = import.meta.env.VITE_API_BASE ?? 'http://127.0.0.1:8000/api/v1';

// The API reports only the checks it can derive from the works data. Progress
// mismatch and missing evidence need the expenditure feed, which is not
// scraped yet, so they are absent rather than shown as zero.
export const CHECK_LABELS = {
  cost_outlier: 'Cost outlier',
  impossible_timeline: 'Impossible timeline',
  duplicate_match: 'Duplicate match',
  stalled: 'Stalled',
  concentration: 'Concentration',
  round_number: 'Round-number amount',
};

export const WORK_STATUSES = [
  'Pending for Sanction', 'Physical Inspection', 'Vendor Identification',
  'Work partially Completed', 'Work Completed', 'Time Estimation', 'NA',
];

async function get(path) {
  const res = await fetch(`${BASE}${path}`);
  if (!res.ok) throw new Error(`${path} -> ${res.status}`);
  return res.json();
}

export async function fetchOverview() {
  const [kpis, checks, ranked, status] = await Promise.all([
    get('/overview/work-data'),
    get('/overview/flag-check'),
    get('/overview/ranked-states'),
    get('/overview/live-status'),
  ]);

  return {
    kpis,
    checkCounts: Object.fromEntries(
      Object.entries(CHECK_LABELS).map(([key, label]) => [label, checks[key] ?? 0]),
    ),
    // Reshaped to the keys the overview view-model already uses, so the map,
    // ranking table and sparklines need no further translation.
    states: ranked.states.map((s) => ({
      id: s.state_code,
      name: s.state,
      monitored: s.works_monitored,
      flagged: s.works_flagged,
      avgRisk: Math.round(s.avg_risk_score),
      trend: s.trend,
    })),
    lastSyncedAt: status.last_synced_at,
  };
}

export async function fetchWorks({ state, status, checkType, query, page, pageSize }) {
  const p = new URLSearchParams();
  if (state) p.set('state', state);
  if (status) p.set('status', status);
  if (checkType) p.set('check_type', checkType);
  if (query) p.set('q', query);
  p.set('limit', pageSize);
  p.set('offset', (page - 1) * pageSize);
  return get(`/works/project_data?${p}`);
}

export async function fetchStateDetail(state, { limit = 20, offset = 0 } = {}) {
  return get(`/overview/state_map/${encodeURIComponent(state)}?limit=${limit}&offset=${offset}`);
}

export async function fetchDossier(workId) {
  return get(`/dossier/${encodeURIComponent(workId)}`);
}

export async function fetchContractors({ limit = 50, offset = 0 } = {}) {
  return get(`/contractors/?limit=${limit}&offset=${offset}`);
}

export async function fetchLiveEvents({ limit = 8 } = {}) {
  return get(`/overview/live-events?limit=${limit}`);
}
