// Client for the MPLADS Oversight API. Hand-written — unlike js/pages, js/state
// and js/data, this file is not regenerated by tools/jsxify.mjs.

const BASE = import.meta.env.VITE_API_BASE ?? 'http://127.0.0.1:8000/api/v1';

// The API reports only the checks it can derive from the works data. Progress
// mismatch and missing evidence need the expenditure feed, which is not
// scraped yet, so they are absent rather than shown as zero.
const CHECK_LABELS = {
  cost_outlier: 'Cost outlier',
  impossible_timeline: 'Impossible timeline',
  duplicate_match: 'Duplicate match',
  stalled: 'Stalled',
  concentration: 'Concentration',
  round_number: 'Round-number amount',
};

async function get(path) {
  const res = await fetch(`${BASE}${path}`);
  if (!res.ok) throw new Error(`${path} -> ${res.status}`);
  return res.json();
}

export async function fetchOverview() {
  const [kpis, checks, ranked, status] = await Promise.all([
    get('/overview/work-data'),
    get('/overview/flag-check'),
    get('/overview/ranked-states'),
    get('/overview/live-status'),
  ]);

  return {
    kpis,
    checkCounts: Object.fromEntries(
      Object.entries(CHECK_LABELS).map(([key, label]) => [label, checks[key] ?? 0]),
    ),
    // Reshaped to the keys the overview view-model already uses, so the map,
    // ranking table and sparklines need no further translation.
    states: ranked.states.map((s) => ({
      id: s.state_code,
      name: s.state,
      monitored: s.works_monitored,
      flagged: s.works_flagged,
      avgRisk: Math.round(s.avg_risk_score),
      trend: s.trend,
    })),
    lastSyncedAt: status.last_synced_at,
  };
}
